'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BOMoldLabelApp.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iApplicationName.
        '''</summary>
        Friend ReadOnly Property PARAM_iApplicationName() As String
            Get
                Return ResourceManager.GetString("PARAM_iApplicationName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iItemNo.
        '''</summary>
        Friend ReadOnly Property PARAM_iItemNo() As String
            Get
                Return ResourceManager.GetString("PARAM_iItemNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iLoc.
        '''</summary>
        Friend ReadOnly Property PARAM_iLoc() As String
            Get
                Return ResourceManager.GetString("PARAM_iLoc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iPrinterName.
        '''</summary>
        Friend ReadOnly Property PARAM_iPrinterName() As String
            Get
                Return ResourceManager.GetString("PARAM_iPrinterName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iStatus.
        '''</summary>
        Friend ReadOnly Property PARAM_iStatus() As String
            Get
                Return ResourceManager.GetString("PARAM_iStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iUserName.
        '''</summary>
        Friend ReadOnly Property PARAM_iUserName() As String
            Get
                Return ResourceManager.GetString("PARAM_iUserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spIMGetBinLabels_MAS.
        '''</summary>
        Friend ReadOnly Property SP_spIMGetBinLabels_MAS() As String
            Get
                Return ResourceManager.GetString("SP_spIMGetBinLabels_MAS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spSettings_MAS.
        '''</summary>
        Friend ReadOnly Property SP_spSettings_MAS() As String
            Get
                Return ResourceManager.GetString("SP_spSettings_MAS", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
